### ISSUE TITLE
Server request

### ISSUE THREAD

**Issue by fogelwinning** [cranki-s/ragemp-serverdumps#1]
Do you take server requests? Or can I get subscription to a tool that dumps?

**Comment by cranki-s** [comment]
yes i take request.

**Comment by fogelwinning** [comment]
Nice, can you try EternalRage.net? play.eternalrage.net:22005

Thanks

**Comment by cranki-s** [comment]
sure, i will do it later then

**Comment by JJiGolem** [comment]
If possible I would suggest r1.smotra.games:22005

Thank you!

**Comment by cranki-s** [comment]
> If possible I would suggest r1.smotra.games:22005
> 
> Thank you!

done

**Comment by fogelwinning** [comment]
> Do you take server requests? Or can I get subscription to a tool that dumps?

Hello, was there any issue with my request? They had nice sync fixes. It's ok if you can't do it

**Comment by cranki-s** [comment]
> erver requests? Or can I ge

nah, i am just was too lazy. i will do it now

**Comment by cranki-s** [comment]
> Nice, can you try EternalRage.net? play.eternalrage.net:22005
> 
> Thanks

i dumped the server but they got an obfuscated client side. so i think it would be better if you just use our eventlogger for the server.

**Comment by fogelwinning** [comment]
> > Nice, can you try EternalRage.net? play.eternalrage.net:22005
> > Thanks
> 
> i dumped the server but they got an obfuscated client side. so i think it would be better if you just use our eventlogger for the server.

Thanks for trying, I'll try later. Could you try play.gta.world:22005 if you can please?

**Comment by JJiGolem** [comment]
> > If possible I would suggest r1.smotra.games:22005
> > Thank you!
> 
> done

Thank you very much! Great job!
