### ISSUE TITLE
I hacked grand rp for money

### ISSUE THREAD

**Issue by Egortttf** [cranki-s/ragemp-serverdumps#10]
They burned it down and updated something in fashion, update the page)

**Comment by Schwarzentoeter** [comment]
Stfu, u is black! Retarded n**i**gger!

**Comment by ravuge** [comment]
cool story bro
but no one cares

**Comment by Egortttf** [comment]
> cool story bro but no one cares
I need them to update the code, because the developers have made a fix

**Comment by Egortttf** [comment]
> Stfu, u is black! Retarded n**i**gger!

And here the Niger is not clear, I condemn such statements

**Comment by Egortttf** [comment]
> I hate n**i**ggers!

This is racism, man, and yes, I'm not a "Negro" as you say, so it's pointless

**Comment by 0x280** [comment]
Stick to the topic, GrandRP update will be pushed later that day.
