### ISSUE TITLE
gtaw

### ISSUE THREAD

**Issue by flyingstartx** [cranki-s/ragemp-serverdumps#17]
greetings,

can you update the gtaworld english dump and maybe add cef please? it is gtw folder in this repo. ip: play.gta.world:22005

thanks

**Comment by 0x280** [comment]
cef added in e634b3dbbb503181402452964dab70fb74a13263, clientside updated in 09715d513fc26893e2328ab68300feaac67e484c

**Comment by PeKrKC** [comment]
how do you give yourself money inside of gtaw with this?
