### ISSUE TITLE
gtaworld

### ISSUE THREAD

**Issue by linkbleu2000** [cranki-s/ragemp-serverdumps#4]
Can you add gtaworld (gtaw)? it is big english/russian server. But have 2 different scrippts. thanks

play.gta.world:22005
play.gta-world.ru:22005

**Comment by cranki-s** [comment]
done

**Comment by linkbleu2000** [comment]
Many thanks for russian version @cranki-s. But can u do the english server as well pls? it is UK flag server on client (play.gta.world:22005)
